export const Selector4 = {
    email: "Enter email...",
    password: "Enter password...",
    login: "Login",
    boardSelection: "body > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > main:nth-child(2) > div:nth-child(1) > div:nth-child(1) > section:nth-child(3) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1)",
    newBucketCreation: "div.Bucket1_AddList_Button__HLscO",
    bucketTitle: "Enter list title...",
    addBucketButton: "Add list",
    newCardCreation: "div.Toggle_AddCard",
    cardTitle: "Enter a title for this card...",
    addCardButton: "Add card",
    selectDescription: "div.listcard_title",
    addDescription: "Add a more detailed description...",
    descriptionTextArea: "textarea.description_textarea",
    descriptionSave: "save",
    checklistButton: "body > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > main:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3)",
    checklistAddButton: "Add",
    button_of_item_addition: "body > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > main:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > button:nth-child(5)",
    addItem: "Add an item",
    itemAdditionButton: "Add",
    checkItem: "input#flexCheckDefault"
}